apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy-app
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: dummy.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dummy-app
            port:
              number: 80
